# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{
    'name': 'All in One Sales Management Bundle App',
    'version': '16.0.0.1',
    'category': 'Sales',
    'summary': 'All sales management tools all in one sales tools all in one sales management all in one sale bundle all in one sales bundle all sales bundle sale advance payment sale price history merge sale order sale multi warehouse automated sales profitability report',
    'description': """
    This odoo app helps user to send mass sales order by email and filter sent sales order and not sent sales orders, user can import sale order from xls or csv file, User can set customer credit limit and blocking limit when it exceeded an auto-generated email will be sent to administrator along with that sale order reference. User also can check sales price history from sale order view, User can aslo add custom fields or tabs from GUI to sale order view. User can also configure and create workflow to set automated flow for sales order and merge sales order with different option. User can also select warehouses on each sale order line and delivery order created based on the warehouse selected on the sale order line. User can also make an advance down payment using the advance payment button in sale order. User also can create and set multiple tags for sale order and use tags as a filter and find records easily in tree view, also they can search tags from the search view. User also can identify the product profitability and return rate with the filtration of Day, Week ,Month and Year. User also can print sales order excel report.""",
    'author': 'BrowseInfo',
    'website': 'https://www.browseinfo.com',
    "price": 89,
    "currency": 'EUR',
    'website': 'https://www.browseinfo.in',
    'depends': ['sale_management', 'account' ,'stock','product','sales_team'],
    'data': [
        'security/saleorder_custom_groups.xml',
        'security/ir.model.access.csv',
        'wizard/advance_payment_views.xml',
        'wizard/sale_excel_report.xml',
        'wizard/excel_report.xml',
        'wizard/wizard_credit_limit.xml',
        'wizard/merge_same_customer_so_views.xml',
        'views/sale_views.xml',
        'views/price_history.xml',
        'views/report_salehistory.xml',
        'views/sale_report_view.xml',
        'views/sale_config_settings_views.xml',
        'views/product_template_inherit.xml',
        'views/product_product_inherit.xml',
        'views/sale_order_views.xml',
        'views/view_main.xml',
        'views/saleorder_custom_field_view.xml',
        'views/res_company_view.xml',
        'views/sale_order_tag.xml',
        'views/import_order_lines_view.xml',
        'views/mass_mail_view.xml',
        'views/view_credit_limit.xml',
        'views/order_merge_view.xml',
        'views/sale_order.xml',
        'views/sale_order_line_merge.xml',
        'views/res_config_settings.xml',
        'edi/customer_credit_limit_mail.xml',
        'report/product_profitability_view.xml',
    
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'live_test_url': 'https://youtu.be/gv3RNZrq3wQ',
    "images": ['static/description/Banner.gif'],
    'license': 'OPL-1',
}
